project_id = "vtmwhvxdgrvaegprmkwg"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
port = 54324
site_url = "https://567bec84-bf31-4c4f-a226-9795b193895b.lovableproject.com"
additional_redirect_urls = [
  "https://localhost:3000",
  "https://567bec84-bf31-4c4f-a226-9795b193895b.lovableproject.com/**",
  "https://preview--pjiae-360.lovable.app/**"
]
jwt_expiry = 3600
enable_signup = true
email_double_confirm_changes = true
enable_manual_linking = false

[edge_functions]
enabled = true
port = 54325

[functions.import-employees]
verify_jwt = true

[functions.enhanced-email-service]
verify_jwt = true

[functions.send-account-welcome]
verify_jwt = true

[functions.send-branded-email]
verify_jwt = true

[functions.confirm-membership]
verify_jwt = false

[functions.invite-reminders]
verify_jwt = false