// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmbwbtpixrbjduftsewp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptYndidHBpeHJiamR1ZnRzZXdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMDYwNTgsImV4cCI6MjA2NzU4MjA1OH0.yuUCxHoJnO5v7rFYAMk68uCUnt-QacrgrBD5rEd2iGI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});